# Welcome to Serverless!
# This file is the main config file for your service.
# For full config options, check the docs:
#    docs.serverless.com
# Happy Coding!

service: neighbourly
tenant: YOUR_TENANT_NAME
app: YOUR_APP_NAME

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: us-east-1
  memorySize: 1024 # optional, in MB, default is 1024
  timeout: 30 # optional, in seconds, default is 6

plugins:
  - serverless-offline

# you can define service wide environment variables here
#  environment:
#    variable1: value1

functions:
  getForBounds:
    handler: handler.getForBounds
    memorySize: 1024 # optional, in MB, default is 1024
    timeout: 30 # optional, in seconds, default is 6
    # Define function environment variables here
    environment:
      DATABASE_URL: YOUR_DATABASE_URL
      GOOGLE_MAPS_KEY: YOUR_GOOGLE_MAPS_KEY
    events:
      - http:
          path: territories/bounds
          method: get
          cors: true
  generateMap:
    handler: handler.generateMap
    memorySize: 1024 # optional, in MB, default is 1024
    timeout: 30 # optional, in seconds, default is 6
    # Define function environment variables here
    environment:
      DATABASE_URL: YOUR_DATABASE_URL
      GOOGLE_MAPS_KEY: YOUR_GOOGLE_MAPS_KEY
    events:
      - http:
          path: map
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                slug: true
